# ✅ NumPy Basics - Exercise Solutions & Validation

Notebook ini berisi solusi dan validasi untuk semua exercise di `01_numpy_basics.ipynb`.

## 📌 Cara Menggunakan:
1. Kerjakan exercise di notebook utama
2. Copy jawaban Anda ke cell yang sesuai di bawah
3. Run validation cell untuk cek jawaban
4. Lihat feedback: ✅ atau ❌

---

In [1]:
# Import NumPy
import numpy as np
print(f"NumPy version: {np.__version__}")

NumPy version: 2.2.6


## Exercise 1: Creating Arrays

**Task:** Buat:
1. Array 1D berisi angka 10-20
2. Matrix 4x4 berisi angka random 0-100
3. Matrix 3x3 dari normal distribution

In [2]:
# PASTE YOUR SOLUTION HERE

# 1. Array 1D (10-20)
arr1 = np.arange(10, 21)  # or np.array([10,11,12,...,20])

# 2. Matrix 4x4 random (0-100)
arr2 = np.random.randint(0, 101, size=(4, 4))

# 3. Matrix 3x3 normal distribution
arr3 = np.random.randn(3, 3)

print("Array 1D:", arr1)
print("\nMatrix 4x4:")
print(arr2)
print("\nMatrix 3x3 (normal):")
print(arr3)

Array 1D: [10 11 12 13 14 15 16 17 18 19 20]

Matrix 4x4:
[[ 40   0 100  63]
 [ 75  25  24  13]
 [  2   4  18  53]
 [ 88  65  18  21]]

Matrix 3x3 (normal):
[[ 1.08453112  0.07715806  1.77680107]
 [-0.88342124 -0.96615957 -1.31158223]
 [ 1.62073682  0.90972287  0.11006339]]


In [ ]:
# ✅ VALIDATION CELL - Run this to check your answer
try:
    # Check arr1 exists and is numpy array
    assert 'arr1' in dir(), "❌ Variable 'arr1' not defined"
    assert isinstance(arr1, np.ndarray), "❌ arr1 should be NumPy array"
    print("✅ arr1 is a NumPy array")
    
    # Check arr1 dimensions and values
    assert arr1.ndim == 1, f"❌ arr1 should be 1D, got {arr1.ndim}D"
    assert len(arr1) == 11, f"❌ arr1 should have 11 elements (10-20), got {len(arr1)}"
    assert arr1[0] == 10, f"❌ First element should be 10, got {arr1[0]}"
    assert arr1[-1] == 20, f"❌ Last element should be 20, got {arr1[-1]}"
    print(f"✅ arr1 correct: {arr1}")
    
    # Check arr2
    assert 'arr2' in dir(), "❌ Variable 'arr2' not defined"
    assert isinstance(arr2, np.ndarray), "❌ arr2 should be NumPy array"
    assert arr2.shape == (4, 4), f"❌ arr2 should be 4x4, got {arr2.shape}"
    assert arr2.min() >= 0 and arr2.max() <= 100, "❌ arr2 values should be 0-100"
    print(f"✅ arr2 is 4x4 matrix with values 0-100")
    
    # Check arr3
    assert 'arr3' in dir(), "❌ Variable 'arr3' not defined"
    assert isinstance(arr3, np.ndarray), "❌ arr3 should be NumPy array"
    assert arr3.shape == (3, 3), f"❌ arr3 should be 3x3, got {arr3.shape}"
    print(f"✅ arr3 is 3x3 matrix from normal distribution")
    
    print("\n🎉 Perfect! All arrays created correctly!")
    print("You understand NumPy array creation!")
    
except AssertionError as e:
    print(str(e))
    print("\n💡 Hints:")
    print("  - arr1: Use np.arange(10, 21)")
    print("  - arr2: Use np.random.randint(0, 101, size=(4,4))")
    print("  - arr3: Use np.random.randn(3, 3)")

---
## Exercise 2: Indexing & Slicing

**Task:** Diberikan matrix, extract:
1. Baris terakhir
2. Kolom pertama
3. Semua nilai yang lebih besar dari 15

In [ ]:
# Sample matrix (given)
data = np.array([[5, 10, 15],
                 [20, 25, 30],
                 [35, 40, 45]])

# PASTE YOUR SOLUTIONS HERE:

# 1. Last row
last_row = data[-1, :]  # or data[-1] or data[2, :]

# 2. First column
first_column = data[:, 0]

# 3. Values > 15
values_gt_15 = data[data > 15]

print("Last row:", last_row)
print("First column:", first_column)
print("Values > 15:", values_gt_15)

In [ ]:
# ✅ VALIDATION CELL
try:
    # Check last_row
    assert 'last_row' in dir(), "❌ Variable 'last_row' not defined"
    expected_last_row = np.array([35, 40, 45])
    assert np.array_equal(last_row, expected_last_row), f"❌ Last row should be {expected_last_row}, got {last_row}"
    print(f"✅ Last row correct: {last_row}")
    
    # Check first_column
    assert 'first_column' in dir(), "❌ Variable 'first_column' not defined"
    expected_first_col = np.array([5, 20, 35])
    assert np.array_equal(first_column, expected_first_col), f"❌ First column should be {expected_first_col}, got {first_column}"
    print(f"✅ First column correct: {first_column}")
    
    # Check values > 15
    assert 'values_gt_15' in dir(), "❌ Variable 'values_gt_15' not defined"
    expected_values = np.array([20, 25, 30, 35, 40, 45])
    assert np.array_equal(values_gt_15, expected_values), f"❌ Values > 15 should be {expected_values}, got {values_gt_15}"
    print(f"✅ Values > 15 correct: {values_gt_15}")
    
    print("\n🎉 Excellent! You mastered NumPy indexing and slicing!")
    print("This is crucial for data manipulation in ML!")
    
except AssertionError as e:
    print(str(e))
    print("\n💡 Hints:")
    print("  - Last row: data[-1, :] or data[-1]")
    print("  - First column: data[:, 0]")
    print("  - Values > 15: data[data > 15]")

---
## Final Exercise: Mini ML Data Preparation

**Task:** Simulasikan data training untuk ML model:
1. Buat dataset 100 samples, 4 features dari normal distribution
2. Normalize setiap feature (mean=0, std=1) - **Standardization**
3. Split menjadi train (80%) dan test (20%)
4. Print shape dan statistics

In [ ]:
# PASTE YOUR SOLUTION HERE

# 1. Create dataset (100 samples, 4 features)
np.random.seed(42)  # For reproducibility
X = np.random.randn(100, 4)

# 2. Normalize (standardize): (X - mean) / std
X_normalized = (X - np.mean(X, axis=0)) / np.std(X, axis=0)

# 3. Train/test split (80/20)
split_idx = 80
X_train = X_normalized[:split_idx]
X_test = X_normalized[split_idx:]

# 4. Print info
print(f"Training set shape: {X_train.shape}")
print(f"Test set shape: {X_test.shape}")
print(f"\nTraining set mean per feature: {np.mean(X_train, axis=0)}")
print(f"Training set std per feature: {np.std(X_train, axis=0)}")

In [ ]:
# ✅ VALIDATION CELL
try:
    # Check X exists
    assert 'X' in dir(), "❌ Variable 'X' not defined"
    assert isinstance(X, np.ndarray), "❌ X should be NumPy array"
    print("✅ Dataset X created")
    
    # Check X shape
    assert X.shape == (100, 4), f"❌ X should be (100, 4), got {X.shape}"
    print(f"✅ X has correct shape: {X.shape}")
    
    # Check X_normalized
    assert 'X_normalized' in dir(), "❌ Variable 'X_normalized' not defined"
    assert X_normalized.shape == (100, 4), f"❌ X_normalized should be (100, 4), got {X_normalized.shape}"
    print(f"✅ X_normalized created with shape: {X_normalized.shape}")
    
    # Check normalization (mean ≈ 0, std ≈ 1)
    mean_normalized = np.mean(X_normalized, axis=0)
    std_normalized = np.std(X_normalized, axis=0)
    
    assert np.allclose(mean_normalized, 0, atol=1e-10), f"❌ Mean should be ~0, got {mean_normalized}"
    print(f"✅ Normalized data has mean ≈ 0: {mean_normalized}")
    
    assert np.allclose(std_normalized, 1, atol=0.01), f"❌ Std should be ~1, got {std_normalized}"
    print(f"✅ Normalized data has std ≈ 1: {std_normalized}")
    
    # Check train/test split
    assert 'X_train' in dir() and 'X_test' in dir(), "❌ X_train or X_test not defined"
    assert X_train.shape == (80, 4), f"❌ X_train should be (80, 4), got {X_train.shape}"
    assert X_test.shape == (20, 4), f"❌ X_test should be (20, 4), got {X_test.shape}"
    print(f"✅ Train/test split correct: {X_train.shape} / {X_test.shape}")
    
    # Check that train+test = total
    assert X_train.shape[0] + X_test.shape[0] == 100, "❌ Train + test should equal 100 samples"
    print("✅ Total samples preserved: 80 + 20 = 100")
    
    print("\n" + "="*60)
    print("🎉🎉🎉 CONGRATULATIONS! 🎉🎉🎉")
    print("="*60)
    print("\nYou completed ALL NumPy exercises!")
    print("\n✅ Skills Mastered:")
    print("  • Creating NumPy arrays")
    print("  • Array indexing & slicing")
    print("  • Data normalization (standardization)")
    print("  • Train/test splitting")
    print("  • Statistical operations")
    print("\n🚀 You're ready for REAL machine learning!")
    print("\n➡️  Next: Learn Pandas for data manipulation!")
    print("="*60)
    
except AssertionError as e:
    print(str(e))
    print("\n💡 Hints:")
    print("  1. X = np.random.randn(100, 4)")
    print("  2. X_normalized = (X - np.mean(X, axis=0)) / np.std(X, axis=0)")
    print("  3. X_train = X_normalized[:80], X_test = X_normalized[80:]")

---

## 🎓 NumPy Skills For Machine Learning

If you've passed all validations, you now know:

### ✅ Core NumPy Skills
- **Array Creation** - zeros, ones, random, arange, linspace
- **Array Operations** - element-wise operations, broadcasting
- **Indexing & Slicing** - 1D, 2D, boolean indexing
- **Shape Manipulation** - reshape, transpose, flatten
- **Mathematical Operations** - sum, mean, std, matrix multiplication
- **Statistical Functions** - For data analysis

### 🎯 ML-Ready Skills
- ✅ **Data representation** as NumPy arrays
- ✅ **Feature normalization** (standardization)
- ✅ **Train/test splitting** for model validation
- ✅ **Matrix operations** foundation for neural networks
- ✅ **Statistical analysis** for data exploration

### 📊 Your Progress
- ✅ 01-python-basics: **COMPLETED**
- ✅ 02-numpy-pandas (NumPy): **COMPLETED**
- ⏭️ Next: 02-numpy-pandas (Pandas)

---

## 💪 Real ML Workflow Preview

What you just did in the final exercise is **exactly** what happens in real ML:

```python
# 1. Load data
X = load_data()  # You created: np.random.randn(100, 4)

# 2. Normalize features (CRITICAL for ML!)
X = (X - X.mean()) / X.std()  # You did this!

# 3. Split train/test
X_train, X_test = split_data(X)  # You did this!

# 4. Train model (coming soon in ML modules!)
model.fit(X_train, y_train)

# 5. Evaluate
score = model.score(X_test, y_test)
```

You've completed steps 1-3! 🎉

---

**Keep up the amazing work! 🚀**