# 🔢 NumPy Basics - Foundation of Scientific Computing

NumPy (Numerical Python) adalah library fundamental untuk scientific computing di Python. Hampir semua library ML (termasuk scikit-learn dan TensorFlow) dibangun di atas NumPy.

## 📋 Outline
1. What is NumPy?
2. Creating Arrays
3. Array Operations
4. Indexing & Slicing
5. Array Shape Manipulation
6. Mathematical Operations
7. Broadcasting
8. Statistical Functions

## 1. What is NumPy?

### Kenapa NumPy?
- ⚡ **Lebih cepat** - 10-100x lebih cepat dari Python lists
- 💾 **Memory efficient** - Menggunakan lebih sedikit memory
- 🧮 **Mathematical operations** - Built-in functions untuk operasi matematika
- 🔗 **Integration** - Bekerja sempurna dengan library ML lainnya

### Import NumPy

In [1]:
import numpy as np

# Check version
print(f"NumPy version: {np.__version__}")

NumPy version: 2.2.6


## 2. Creating Arrays

### From Python Lists

### 📖 Apa itu Creating Arrays?

**Creating Arrays** adalah proses **membuat struktur data NumPy array** dari berbagai sumber. Ini adalah langkah pertama dalam setiap operasi NumPy - tanpa array, tidak ada yang bisa dilakukan!

### 🎯 Tentang Apa Ini?

Topik ini mengajarkan berbagai cara untuk "membawa data" masuk ke dalam NumPy ecosystem:

1. **Dari data yang sudah ada** (Python lists) - convert existing data
2. **Generate dari scratch** (zeros, ones, arange) - create data patterns  
3. **Random generation** (np.random) - create test data atau initialize values

**Analogi:** Seperti "import data" ke Excel - bisa dari file, bisa ketik manual, atau bisa generate pattern.

### 💡 Mengapa Penting untuk ML?

- **Initialize weights** - Neural networks start dengan random weights
- **Create test data** - Generate synthetic datasets untuk testing
- **Prepare data structures** - Siapkan "containers" untuk hasil computations

In [4]:
# 1D Array (Vector)
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr_1d)
print("Shape:", arr_1d.shape)
print("Dimensions:", arr_1d.ndim)
print("Data Type:", arr_1d.dtype)
print()

1D Array: [1 2 3 4 5]
Shape: (5,)
Dimensions: 1
Data Type: int64



In [3]:
# 2D Array (Matrix)
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("2D Array:")
print(arr_2d)
print("\nShape:", arr_2d.shape)  # (rows, columns)
print("Dimensions:", arr_2d.ndim)
print("Size (total elements):", arr_2d.size)

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Shape: (3, 3)
Dimensions: 2
Size (total elements): 9


### Built-in Array Creation Functions

In [5]:
# Array of zeros
zeros = np.zeros((3, 4))  # 3 rows, 4 columns
print("Zeros:")
print(zeros)
print()

# Array of ones
ones = np.ones((2, 3))
print("Ones:")
print(ones)
print()

# Array with constant value
full = np.full((2, 2), 7)
print("Full (7s):")
print(full)

Zeros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones:
[[1. 1. 1.]
 [1. 1. 1.]]

Full (7s):
[[7 7]
 [7 7]]


In [6]:
# Identity matrix (important for ML!)
0 = np.eye(3)
print("Identity Matrix:")
print(identity)
print()

# Range of values
range_arr = np.arange(0, 10, 2)  # start, stop, step
print("Arange:", range_arr)
print()

# Evenly spaced values
linspace_arr = np.linspace(0, 1, 5)  # start, stop, number of points
print("Linspace:", linspace_arr)

Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Arange: [0 2 4 6 8]

Linspace: [0.   0.25 0.5  0.75 1.  ]


### Random Arrays (Very Important for ML!)

In [7]:
# Random numbers between 0 and 1
random_arr = np.random.random((3, 3))
print("Random (0-1):")
print(random_arr)
print()

# Random integers
random_int = np.random.randint(0, 10, size=(3, 3))  # 0-10, 3x3 array
print("Random Integers:")
print(random_int)
print()

# tNormal distribution (Gaussian) - SANGAT PENTING untuk ML!
normal_arr = np.random.randn(3, 3)  # Mean=0, Std=1
print("Normal Distribution:")
print(normal_arr)

Random (0-1):
[[0.80337473 0.33209068 0.58806634]
 [0.45553877 0.85976995 0.1201341 ]
 [0.73514486 0.04194891 0.03830957]]

Random Integers:
[[7 0 1]
 [8 3 1]
 [2 7 5]]

Normal Distribution:
[[-1.36569888 -1.38423288 -0.4901699 ]
 [-1.7706216  -1.17800231 -0.53786692]
 [-2.07435588  0.21386605 -0.46786453]]


### 💡 Exercise 1
Buat:
1. Array 1D berisi angka 10-20
2. Matrix 4x4 berisi angka random 0-100
3. Matrix 3x3 dari normal distribution

In [12]:
# Tulis kode Anda di sini
import numpy as np
# 1. Array 1D (10-20)
arr1 = np.arange(10, 21)
print("Array 1D 10-20: ", arr1)

# 2. Matrix 4x4 random (0-100)
arr2 = np.random.randint(0, 101, size=(4, 4))
print("Matrix 4x4 random: ", arr2)

# 3. Matrix 3x3 normal distribution
arr3 = np.random.randn(3, 3)
print("Matrix 3x3 normal distribution: ", arr2)

Array 1D 10-20:  [10 11 12 13 14 15 16 17 18 19 20]
Matrix 4x4 random:  [[21 62 53 47]
 [54 19 88 90]
 [43 70 51 85]
 [ 5 58 18  5]]
Matrix 3x3 normal distribution:  [[21 62 53 47]
 [54 19 88 90]
 [43 70 51 85]
 [ 5 58 18  5]]


---

## 📚 Section 3: Array Operations

### 📖 Apa itu Array Operations?

**Array Operations** adalah **operasi matematika yang dilakukan pada SELURUH array sekaligus** tanpa perlu loop. NumPy melakukan operasi element-by-element secara otomatis (vectorization).

### 🎯 Tentang Apa Ini?

Bayangkan punya 1 juta angka dan ingin kalikan semuanya dengan 2:
- **Cara biasa (Python list):** Loop 1 juta kali - SLOW! ⏳
- **Cara NumPy:** Satu operasi `array * 2` - INSTANT! ⚡

**Yang akan dipelajari:**
1. **Basic arithmetic** (+, -, *, /) - operasi dasar pada seluruh array
2. **Universal functions (ufuncs)** - fungsi optimized (sin, cos, exp, log, sqrt)
3. **Broadcasting** - operasi pada arrays dengan shape berbeda

### 💡 Mengapa Penting?

Ini adalah **inti kekuatan NumPy**! Vectorization makes:
- ✅ Code lebih clean & readable
- ✅ Execution 50-100x faster
- ✅ Less bugs (no loop index errors)
- ✅ Data normalization, feature scaling, activation functions - semua pakai ini!

**Real ML use:** Normalize features → `(X - mean) / std` - satu line untuk jutaan data!

## 3. Array Operations

### Element-wise Operations

In [3]:
# Create sample arrays
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print("Array a:", a)
print("Array b:", b)
print()

# Addition
print("a + b:", a + b)

# Subtraction
print("a - b:", a - b)

# Multiplication
print("a * b:", a * b)

# Division
print("b / a:", b / a)

# Power
print("a ** 2:", a ** 2)

Array a: [1 2 3 4]
Array b: [10 20 30 40]

a + b: [11 22 33 44]
a - b: [ -9 -18 -27 -36]
a * b: [ 10  40  90 160]
b / a: [10. 10. 10. 10.]
a ** 2: [ 1  4  9 16]


## 4. Indexing & Slicing

---

## 📍 Section 4: Indexing & Slicing

### 📖 Apa itu Indexing & Slicing?

- **Indexing** = cara **mengakses elemen tertentu** dalam array (seperti ambil 1 cell di Excel)
- **Slicing** = cara **mengambil subset/potongan** array (seperti select range A1:D10 di Excel)

### 🎯 Tentang Apa Ini?

Dalam ML, Anda **TIDAK PERNAH** process seluruh dataset sekaligus. Anda selalu perlu:
- ✂️ Ambil baris tertentu (sample tertentu)
- 📊 Ambil kolom tertentu (feature tertentu)
- 🔍 Filter data berdasarkan kondisi (data dengan nilai > threshold)
- 🔀 Split data (training set vs test set)

**4 cara akses data:**

1. **Basic indexing:** `arr[2]` - akses by position
2. **Slicing:** `arr[1:5]` - ambil range
3. **Boolean indexing:** `arr[arr > 10]` - filter by condition ⭐ (POWERFUL!)
4. **Fancy indexing:** `arr[[0, 2, 5]]` - akses multiple indices

**Analogi:** Seperti SQL `WHERE` clause, tapi untuk arrays!

### 💡 Mengapa Penting?

Every ML pipeline needs:
- Select features: `X = data[:, :-1]` (all columns except last)
- Select target: `y = data[:, -1]` (last column)
- Filter outliers: `clean_data = data[data < threshold]`
- Train/test split: `train = data[:800]`, `test = data[800:]`

**Tidak bisa ML tanpa indexing/slicing!**

In [4]:
# 1D Array indexing
arr = np.array([10, 20, 30, 40, 50])
print("Array:", arr)
print("First element:", arr[0])
print("Last element:", arr[-1])
print("First 3 elements:", arr[0:3])
print("Every other element:", arr[::2])

Array: [10 20 30 40 50]
First element: 10
Last element: 50
First 3 elements: [10 20 30]
Every other element: [10 30 50]


In [5]:
# 2D Array indexing (PENTING untuk ML!)
matrix = np.array([[1,  2,  3,  4],
                   [5,  6,  7,  8],
                   [9, 10, 11, 12]])

print("Matrix:")
print(matrix)
print()

# Access element [row, column]
print("Element at [0, 1]:", matrix[0, 1])  # First row, second column
print("Element at [2, 3]:", matrix[2, 3])  # Third row, fourth column
print()

# Select entire row
print("First row:", matrix[0, :])
print("Second row:", matrix[1, :])
print()

# Select entire column
print("First column:", matrix[:, 0])
print("Last column:", matrix[:, -1])
print()

# Slice submatrix
print("Submatrix [0:2, 1:3]:")
print(matrix[0:2, 1:3])

Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Element at [0, 1]: 2
Element at [2, 3]: 12

First row: [1 2 3 4]
Second row: [5 6 7 8]

First column: [1 5 9]
Last column: [ 4  8 12]

Submatrix [0:2, 1:3]:
[[2 3]
 [6 7]]


### Boolean Indexing (Very Useful!)

In [6]:
# Filter elements based on condition
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Create boolean mask
mask = arr > 5
print("Mask (arr > 5):", mask)
print("Filtered values:", arr[mask])
print()

# Direct filtering
print("Even numbers:", arr[arr % 2 == 0])
print("Numbers between 3 and 7:", arr[(arr >= 3) & (arr <= 7)])

Mask (arr > 5): [False False False False False  True  True  True  True  True]
Filtered values: [ 6  7  8  9 10]

Even numbers: [ 2  4  6  8 10]
Numbers between 3 and 7: [3 4 5 6 7]


### 💡 Exercise 2
Diberikan matrix berikut, extract:
1. Baris terakhir
2. Kolom pertama
3. Semua nilai yang lebih besar dari 15

In [10]:
# Sample matrix
data = np.array([[5, 10, 15],
                 [20, 25, 30],
                 [35, 40, 45]])

# Your solutions:
# 1. Last row
print(data[0, :])

# 2. First column
print(data[:, 0])
# 3. Values > 15
print(data[(data > 15)])

[ 5 10 15]
[ 5 20 35]
[20 25 30 35 40 45]


## 5. Array Shape Manipulation

---

## 🔄 Section 5: Array Shape Manipulation

### 📖 Apa itu Shape Manipulation?

**Shape Manipulation** adalah **mengubah dimensi/bentuk array TANPA mengubah data**-nya. Same data, different "packaging"!

**Contoh:** Array dengan 12 elemen bisa berbentuk:
- 1D: `(12,)` - single row
- 2D: `(3, 4)` - 3 rows, 4 columns
- 2D: `(4, 3)` - 4 rows, 3 columns
- 3D: `(2, 2, 3)` - 2 layers of 2x3

Semuanya contain **12 elements yang sama**!

### 🎯 Tentang Apa Ini?

Machine Learning models **SANGAT PARTICULAR** tentang input shape:
- 🖼️ Image classifier expects: `(batch_size, height, width, channels)`
- 🧠 Dense layer expects: `(batch_size, features)`
- 📈 RNN expects: `(batch_size, timesteps, features)`

**Wrong shape = ERROR!** Jadi Anda HARUS bisa reshape data.

**Operations yang akan dipelajari:**

1. **Reshape** - ubah dimensions: `(12,) → (3, 4)`
2. **Flatten** - collapse to 1D: `(3, 4) → (12,)`
3. **Transpose** - flip axes: `(3, 4) → (4, 3)`
4. **Expand dims** - tambah axis: `(3, 4) → (1, 3, 4)`

**Analogi:** Seperti pack 12 telur - bisa 1 row of 12, atau 3 rows of 4, atau 2 boxes of 6. Same eggs, different arrangement! 🥚

### 💡 Mengapa Penting?

**Real ML scenarios:**
- Flatten image: `(28, 28) → (784,)` for neural network input
- Add batch dimension: `(28, 28) → (1, 28, 28)` for single prediction
- Reshape predictions: `(100,) → (100, 1)` for concatenation

In [11]:
# Reshape array
arr = np.arange(1, 13)
print("Original (1D):", arr)
print("Shape:", arr.shape)
print()

# Reshape to 3x4 matrix
matrix_3x4 = arr.reshape(3, 4)
print("Reshaped to 3x4:")
print(matrix_3x4)
print()

# Reshape to 2x6
matrix_2x6 = arr.reshape(2, 6)
print("Reshaped to 2x6:")
print(matrix_2x6)

Original (1D): [ 1  2  3  4  5  6  7  8  9 10 11 12]
Shape: (12,)

Reshaped to 3x4:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Reshaped to 2x6:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [13]:
# Transpose (flip rows and columns)
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

print("Original (2x3):")
print(matrix)
print()

print("Transposed (3x2):")
print(matrix.T)

Original (2x3):
[[1 2 3]
 [4 5 6]]

Transposed (3x2):
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# Flatten (convert to 1D)
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

print("Original 2D:")
print(matrix)
print()

flattened = matrix.flatten()
print("Flattened:", flattened)

## 6. Mathematical Operations

---

## 🧮 Section 6: Mathematical Operations

### 📖 Apa itu Mathematical Operations?

**Mathematical Operations** adalah **fungsi-fungsi matematika yang bekerja pada arrays** - dari simple (sum, mean) sampai advanced (matrix multiplication, eigenvalues).

**Beda dengan Array Operations (Section 3):**
- **Array Operations** fokus pada **element-wise ops** (setiap element)
- **Mathematical Operations** fokus pada **aggregate operations** (reduce array) dan **linear algebra**

### 🎯 Tentang Apa Ini?

Dalam ML, hampir **SEMUA algorithm** adalah math operations!

**📊 Statistics & Aggregations:**
- Calculate `mean`/`std` untuk **normalization**
- Find `min`/`max` untuk **scaling**
- Compute `variance` untuk **feature analysis**

**🔢 Linear Algebra:**
- `Matrix multiplication` = Neural network forward pass
- `Dot product` = Similarity calculation
- `Eigenvalues` = PCA dimensionality reduction

**Yang akan dipelajari:**

1. **Aggregations** - reduce array to single value (atau per-axis)
   - `sum()`, `mean()`, `std()`, `min()`, `max()`, `median()`

2. **Axis operations** - aggregate along specific dimension
   - Sum per row vs sum per column
   - Mean of each feature across samples

3. **Matrix operations** - linear algebra (the math behind ML!)
   - Dot product: `np.dot(A, B)`
   - Matrix multiply: `A @ B`

**Analogi:** 
- Aggregations seperti "Total" button di Excel
- Matrix ops seperti Excel solver, tapi **much more powerful**!

### 💡 Mengapa Penting?

**Every ML algorithm uses these:**
- **Linear Regression:** Matrix operations untuk solve coefficients
- **Neural Networks:** Matrix multiplication di every layer
- **K-Means:** Distance calculations using dot products
- **PCA:** Eigenvalue decomposition

**Real example:** Standardize data → `X_std = (X - X.mean(axis=0)) / X.std(axis=0)`

In [ ]:
# Basic math functions
arr = np.array([1, 2, 3, 4, 5])

print("Array:", arr)
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard Deviation:", np.std(arr))
print("Variance:", np.var(arr))
print("Min:", np.min(arr))
print("Max:", np.max(arr))

In [ ]:
# Operations on 2D arrays
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Matrix:")
print(matrix)
print()

print("Sum of all elements:", np.sum(matrix))
print("Sum of each column:", np.sum(matrix, axis=0))  # axis=0: columns
print("Sum of each row:", np.sum(matrix, axis=1))     # axis=1: rows
print()

print("Mean of all:", np.mean(matrix))
print("Mean of each column:", np.mean(matrix, axis=0))

### Matrix Multiplication (CRUCIAL for ML!)

In [ ]:
# Element-wise multiplication
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print()

# Element-wise (Hadamard product)
print("Element-wise multiplication (A * B):")
print(A * B)
print()

# Matrix multiplication (Dot product)
print("Matrix multiplication (A @ B):")
print(A @ B)
# or
print("\nMatrix multiplication (np.dot(A, B)):")
print(np.dot(A, B))

## 7. Broadcasting

Broadcasting adalah aturan NumPy untuk operasi pada arrays dengan shape yang berbeda.

---

## 📡 Section 7: Broadcasting

### 📖 Apa itu Broadcasting?

**Broadcasting** adalah **set aturan otomatis** yang memungkinkan NumPy melakukan operasi pada arrays dengan **shapes yang berbeda** - tanpa perlu manually expand arrays!

**Contoh simple:**
```python
arr = np.array([1, 2, 3])  # Shape: (3,)
arr + 10  # → [11, 12, 13]
```

**Kenapa bisa?** NumPy automatically "broadcasts" scalar `10` menjadi `[10, 10, 10]` behind the scenes! ✨

### 🎯 Tentang Apa Ini?

Broadcasting adalah "magic" yang makes NumPy code **clean & efficient**. 

**Without broadcasting (manual):**
```python
scalar = 10
expanded = np.array([scalar, scalar, scalar])  # Repeat manually 😫
result = arr + expanded
```

**WITH broadcasting (automatic):**
```python
result = arr + 10  # NumPy does expansion automatically! 🎉
```

**Yang akan dipelajari:**

1. **Broadcasting rules** - kapan broadcasting works, kapan tidak
   - Rule 1: Dimensions compared from right to left
   - Rule 2: Compatible if dimensions equal OR one is 1

2. **Common patterns:**
   - Add scalar to array: `(100,) + scalar`
   - Add vector to matrix (row-wise): `(100, 10) + (10,)`
   - Add vector to matrix (column-wise): `(100, 10) + (100, 1)`

3. **Performance benefits** - avoid loops dan explicit copying

**Analogi:** Seperti Excel auto-fill - ketik formula di 1 cell, drag ke bawah, formula automatically adjust. Broadcasting does similar "auto-adjustment" for arrays!

### 💡 Mengapa Penting?

Broadcasting makes code:
- ✅ **Cleaner** - no manual expansion needed
- ✅ **Faster** - no unnecessary copying
- ✅ **More readable** - intent is clear

**Real ML use cases:**
- Add bias to predictions: `predictions + bias` (broadcast bias to all samples)
- Normalize features: `(X - mean) / std` (broadcast mean/std to all rows)
- Center data: `X - X.mean(axis=0)` (broadcast column means)

In [ ]:
# Broadcasting with scalar
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("Original:")
print(arr)
print()

# Add 10 to all elements (broadcasting)
print("Add 10 to all:")
print(arr + 10)

In [ ]:
# Broadcasting with 1D array
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

row_vector = np.array([10, 20, 30])

print("Matrix:")
print(matrix)
print("\nRow vector:", row_vector)
print()

# Add row vector to each row of matrix
print("Matrix + Row vector:")
print(matrix + row_vector)
print()

# Multiply each row by row vector
print("Matrix * Row vector:")
print(matrix * row_vector)

## 8. Statistical Functions

---

## 📈 Section 8: Statistical Functions

### 📖 Apa itu Statistical Functions?

**Statistical Functions** adalah **fungsi-fungsi untuk analyze distribusi dan properties dari data** - mean, median, percentiles, correlation, dll.

Ini adalah subset dari Mathematical Operations (Section 6), tapi fokus specifically pada **statistical analysis**.

### 🎯 Tentang Apa Ini?

Before building ANY ML model, Anda HARUS understand data Anda:

**📊 Questions to answer:**
- What's the average value? (central tendency)
- How spread out is the data? (variance/std)
- Are there outliers? (min/max, percentiles)
- Is data normally distributed? (skewness)
- Do features correlate? (correlation matrix)

This is **Exploratory Data Analysis (EDA)** - critical first step!

**Functions yang akan dipelajari:**
- `mean()`, `median()`, `mode()` - central tendency
- `std()`, `var()` - spread/dispersion
- `min()`, `max()`, `percentile()` - range & outliers
- `corrcoef()` - correlation between features

### 💡 Mengapa Penting?

**Bad data = Bad model, no matter how good the algorithm!**

Statistical analysis helps:
- 🔍 **Detect issues:** Missing values, outliers, skewed distributions
- 🎯 **Choose preprocessing:** Which features need scaling? Transformation?
- 🧮 **Feature engineering:** Which features are important? Related?
- ✅ **Validate:** Does data make sense? Any anomalies?

**Real example:** 
Before training model, check: `X.mean()`, `X.std()`, `X.min()`, `X.max()` - if mean >> std, features need scaling!

In [ ]:
# Create sample data (scores of students)
np.random.seed(42)  # For reproducibility
scores = np.random.randint(60, 100, size=20)

print("Student Scores:", scores)
print()

print(f"Mean: {np.mean(scores):.2f}")
print(f"Median: {np.median(scores)}")
print(f"Std Dev: {np.std(scores):.2f}")
print(f"Variance: {np.var(scores):.2f}")
print(f"Min: {np.min(scores)}")
print(f"Max: {np.max(scores)}")
print(f"Range: {np.ptp(scores)}")  # peak to peak (max - min)
print()

# Percentiles
print(f"25th percentile: {np.percentile(scores, 25)}")
print(f"50th percentile (median): {np.percentile(scores, 50)}")
print(f"75th percentile: {np.percentile(scores, 75)}")

### 💡 Final Exercise: Mini ML Data Preparation

Simulasikan data training untuk ML model:
1. Buat dataset 100 samples, 4 features dari normal distribution
2. Normalize setiap feature (mean=0, std=1)
3. Split menjadi train (80%) dan test (20%)
4. Print shape dan statistics

In [ ]:
# Your solution here

# 1. Create dataset (100 samples, 4 features)
np.random.seed(42)
X = 

# 2. Normalize (standardize)
X_normalized = 

# 3. Train/test split (80/20)
split_idx = 
X_train = 
X_test = 

# 4. Print info
print(f"Training set shape: {X_train.shape}")
print(f"Test set shape: {X_test.shape}")
print(f"\nTraining set mean: {np.mean(X_train, axis=0)}")
print(f"Training set std: {np.std(X_train, axis=0)}")

## 🎉 Congratulations!

Anda sudah menguasai NumPy basics!

### ✅ Yang Sudah Dipelajari:
- Creating arrays (zeros, ones, random, etc.)
- Array operations (element-wise, broadcasting)
- Indexing & slicing (1D and 2D)
- Shape manipulation (reshape, transpose, flatten)
- Mathematical operations
- Matrix multiplication
- Statistical functions

### 🎯 NumPy Skills untuk ML:
- ✅ Data representation as arrays
- ✅ Feature normalization
- ✅ Matrix operations for neural networks
- ✅ Statistical analysis
- ✅ Data preprocessing

### ➡️ Next Step:
Lanjut ke `02_pandas_dataframes.ipynb` untuk belajar data manipulation dengan Pandas!

---

### 📚 Resources:
- [NumPy Documentation](https://numpy.org/doc/stable/)
- [NumPy for Absolute Beginners](https://numpy.org/doc/stable/user/absolute_beginners.html)
- [NumPy Cheatsheet](https://www.datacamp.com/cheat-sheet/numpy-cheat-sheet-data-analysis-in-python)